FROM node:18-alpine
WORKDIR /app

RUN apk add --no-cache curl

COPY package*.json ./
COPY prisma ./prisma/

RUN HUSKY=0 npm ci --only=production --ignore-scripts
RUN npx prisma generate
RUN npm install -g tsx

COPY scripts/letterboxd/update-popularity-daily.ts ./scripts/letterboxd/

CMD ["tsx", "scripts/letterboxd/update-popularity-daily.ts"]
