name: Deploy to Hetzner VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ${{ secrets.VPS_PATH }}
          
          # Pull últimos cambios
          git pull origin main
          
          # Rebuild y restart Docker
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          # Verificar que está corriendo
          docker ps
          echo "✅ Deployment completado"