name: Deploy to Hetzner VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Navegar al directorio del proyecto
          cd ${{ secrets.VPS_PATH }}
          
          # Pull últimos cambios
          git pull origin main
          
          # Instalar dependencias
          npm ci
          
          # Generar Prisma Client
          npx prisma generate
          
          # Build del proyecto
          npm run build
          
          # Recargar PM2
          pm2 reload cinenacional --update-env
          pm2 save
          
          # Opcional: Limpiar cache antiguo
          # rm -rf .next/cache