# .github/workflows/generate-structure.yml
name: Generate Project Structure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-structure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        persist-credentials: true
    
    - name: Generate structure JSON
      run: |
        cat > generate-structure.js << 'EOF'
        const fs = require('fs');
        const path = require('path');

        function scanDirectory(dir, base = '') {
          const items = fs.readdirSync(dir);
          const result = {};
          
          items.forEach(item => {
            if (item.startsWith('.') || 
                item === 'node_modules' || 
                item === '.next' ||
                item === 'out' ||
                item === 'coverage' ||
                item === 'project-structure.json') return;
            
            const fullPath = path.join(dir, item);
            const relativePath = path.join(base, item).replace(/\\/g, '/');
            
            try {
              const stats = fs.statSync(fullPath);
              
              if (stats.isDirectory()) {
                const subResult = scanDirectory(fullPath, relativePath);
                if (Object.keys(subResult).length > 0) {
                  result[item] = subResult;
                }
              } else if (item.match(/\.(ts|tsx|js|jsx|json|css|scss|md|sql|prisma|env\.example)$/)) {
                result[item] = `https://raw.githubusercontent.com/diegopapic/cinenacional/main/${relativePath}`;
              }
            } catch (error) {
              console.error(`Error procesando ${fullPath}:`, error.message);
            }
          });
          
          return result;
        }

        const structure = {
          timestamp: new Date().toISOString(),
          repository: "diegopapic/cinenacional",
          branch: "main",
          commit: "${{ github.sha }}",
          structure: scanDirectory('.'),
          instructions: "INSTRUCCIONES PARA CLAUDE: Este es un mapa completo del repositorio generado automáticamente. Cada archivo tiene una URL que puedes usar con web_fetch para leer su contenido."
        };

        fs.writeFileSync('project-structure.json', JSON.stringify(structure, null, 2));
        console.log('✅ Estructura generada exitosamente');
        EOF

        node generate-structure.js

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add project-structure.json
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update project structure [skip ci]"
          git push
        fi